{
  "properties" : { },
  "id" : "4e036dd00b6c4874b30598dd3512ccb2",
  "script" : null,
  "groupId" : "0d01c50a5cf9471788deb7210f70f3fa",
  "name" : "send",
  "createTime" : null,
  "updateTime" : 1774577033663,
  "lock" : null,
  "createBy" : "admin",
  "updateBy" : "admin",
  "path" : "send",
  "method" : "POST",
  "parameters" : [ ],
  "options" : [ {
    "name" : "wrap_request_parameter",
    "value" : "disable-cache",
    "description" : "包装请求参数到一个变量中",
    "required" : false,
    "dataType" : "String",
    "type" : null,
    "defaultValue" : null,
    "validateType" : null,
    "error" : null,
    "expression" : null,
    "children" : null
  }, {
    "name" : "permission",
    "value" : "datastat",
    "description" : "允许拥有该权限的访问",
    "required" : false,
    "dataType" : "String",
    "type" : null,
    "defaultValue" : null,
    "validateType" : null,
    "error" : null,
    "expression" : null,
    "children" : null
  } ],
  "requestBody" : "",
  "headers" : [ ],
  "paths" : [ ],
  "responseBody" : "{\n    \"code\": 1,\n    \"message\": \"success\",\n    \"data\": null,\n    \"timestamp\": 1774332638700,\n    \"executeTime\": 1\n}",
  "description" : null,
  "requestBodyDefinition" : null,
  "responseBodyDefinition" : null
}
================================

return null
